// Generated by img2icon, grey channel

#include <mono_icon.h>

namespace mono { namespace display { 
	static const unsigned char thermWarmBitmap[] = {
160, 172, 166, 160, 155, 149, 143, 137, 133, 160, 
160, 171, 167, 161, 155, 149, 143, 138, 133, 160, 
0 };

	const MonoIcon thermWarm = {
		10, 2, (uint8_t*) thermWarmBitmap
	};
} }
