// Generated by img2icon, grey channel

#include <mono_icon.h>

namespace mono { namespace display { 
	static const unsigned char thermColdBitmap[] = {
196, 114, 110, 106, 103, 99, 96, 92, 89, 196, 
196, 113, 110, 107, 104, 99, 95, 93, 89, 196, 
0 };

	const MonoIcon thermCold = {
		10, 2, (uint8_t*) thermColdBitmap
	};
} }
